server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/database
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
#    url: jdbc:h2:mem:maindb
  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
#  h2:
#    console:
#      path: /h2-console
#      settings:
#        web-allow-others: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  data:
    rest:
      basePath: /datarest

  jackson:
    serialization:
      fail-on-empty-beans: false

management:
  endpoints:
    web:
      exposure:
        include: health, logfile, prometheus
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

logging:
  file:
    name: logs/application.log
  level:
    root: INFO
    ru.otus.hw.services: DEBUG
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"